spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: local  # local, test, dev, real로 분류

  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # window
    #    url: jdbc:h2:~/test           # mac
    username: sa
    password:
    driver-class-name: org.h2.Driver
#
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mariadb://cocktaildb.csmn3giwqma1.ap-northeast-2.rds.amazonaws.com:3306/cocktaildb
#      username: root
#      password: cocktailadmin135!
#      driver-class-name: org.mariadb.jdbc.Driver

  h2.console:
    enabled: true
    path: /h2-console
    settings:
      web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.default_batch_fetch_size: 20

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: "218531279276-apbi76v06s2p4se8hfuiggcik31j77te.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile,email
          # NAVER oauth2 setting
          naver:
            client-id: sy5KwibNCyfgRPptEwPy
            client-secret: mygD4ECTDX
            redirect_uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            client-name: Naver
          kakao:
            client-id: 2601e27014355cb9e0e75498be5b612c
            client-name: Kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            # http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

  app:
    auth:
      token-secret: devbeekei-token-secret-key
      token-expiration-time: 1209600000
    oauth2:
      authorized-redirect-uris:
        - http://localhost:8080/auth/token

  output.ansi.enabled: always  # terminal color