spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev  # local, test, dev, real로 분류

  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # window
  #    url: jdbc:h2:~/test           # mac
  #    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1 # ?????
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2.console:
    enabled: true
    path: /h2-console
    settings:
      web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect   # H2Dialect, MySQL57Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: "218531279276-apbi76v06s2p4se8hfuiggcik31j77te.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile,email
  app:
    auth:
      token-secret: devbeekei-token-secret-key
      token-expiration-time: 1209600000
    oauth2:
      authorized-redirect-uris:
        - http://localhost:8080/auth/token

  output.ansi.enabled: always  # terminal color


