# This is a basic workflow to help you get started with Actions

name: deploy

# test
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name : deploy to stage
    runs-on: ubuntu-20.04
        
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version : 11

      - name: Grant excute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make Zip File
        run: zip cocktail.zip ./build/libs/cocktail-0.0.1-SNAPSHOT.jar

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 cocktail.zip s3://deploy-cocktail/public/
      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name cocktail-api-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name deploy-group
          --s3-location bucket=deploy-cocktail,bundleType=zip,key=public/cocktail.zip
